// Code generated by "stringer -type=Cmd"; DO NOT EDIT.

package emux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdClose-0]
	_ = x[CmdConnect-160]
	_ = x[CmdConnected-161]
	_ = x[CmdDisconnect-192]
	_ = x[CmdDisconnected-193]
	_ = x[CmdData-176]
}

const (
	_Cmd_name_0 = "CmdClose"
	_Cmd_name_1 = "CmdConnectCmdConnected"
	_Cmd_name_2 = "CmdData"
	_Cmd_name_3 = "CmdDisconnectCmdDisconnected"
)

var (
	_Cmd_index_1 = [...]uint8{0, 10, 22}
	_Cmd_index_3 = [...]uint8{0, 13, 28}
)

func (i Cmd) String() string {
	switch {
	case i == 0:
		return _Cmd_name_0
	case 160 <= i && i <= 161:
		i -= 160
		return _Cmd_name_1[_Cmd_index_1[i]:_Cmd_index_1[i+1]]
	case i == 176:
		return _Cmd_name_2
	case 192 <= i && i <= 193:
		i -= 192
		return _Cmd_name_3[_Cmd_index_3[i]:_Cmd_index_3[i+1]]
	default:
		return "Cmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
